# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cphg-millerlab-plaqviewdevatac-dev-deployment
#   namespace: millerlab
#   labels:
#     app: cphg-millerlab-plaqviewdevatac-dev
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: cphg-millerlab-plaqviewdevatac-dev
#   template:
#     metadata:
#       labels:
#         app: cphg-millerlab-plaqviewdevatac-dev
#     spec:
#       volumes:
#       - name: cphg-millerlab-plaqviewdevatac-dev-nfs-volume
#         persistentVolumeClaim:
#           claimName: cphg-millerlab-plaqviewdevatac-dev-nfs-pvc # name of pvc
#       containers:
#       - name: cphg-millerlab-plaqviewdevatac-dev-container
#         image: quay.io/wfma888/plaqviewatac:dev
#         ports:
#         - containerPort: 80
#         volumeMounts:
#         - name: cphg-millerlab-plaqviewdevatac-dev-nfs-volume
#           mountPath: /srv/shiny-server/data # mount inside of container
# #        env:
# #        - name:
# #          value: ""
#         resources:
#           requests:
#             memory: "10000Mi"
#             cpu: "0.5"
#           limits:
#             memory: "11000Mi"
#             cpu: "1"
            
