# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cphg-millerlab-plaqviewdev-deployment
#   namespace: millerlab
#   labels:
#     app: cphg-millerlab-plaqviewdev
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: cphg-millerlab-plaqviewdev
#   template:
#     metadata:
#       labels:
#         app: cphg-millerlab-plaqviewdev
#     spec:
#       volumes:
#       - name: cphg-millerlab-plaqviewdev-nfs-volume
#         persistentVolumeClaim:
#           claimName: cphg-millerlab-plaqviewdev-nfs-pvc # name of pvc
#       containers:
#       - name: cphg-millerlab-plaqviewdev-container
#         image: quay.io/wfma888/plaqview:{{ .Values.version.plaqviewdev }}
#         ports:
#         - containerPort: 80
#         volumeMounts:
#         - name: cphg-millerlab-plaqviewdev-nfs-volume
#           mountPath: /srv/shiny-server/data # mount inside of container
# #        env:
# #        - name:
# #          value: ""
#         resources:
#           requests:
#             memory: "10000Mi"
#             cpu: "0.5"
#           limits:
#             memory: "11000Mi"
#             cpu: "1"
            
