apiVersion: v1
kind: Service
metadata:
  name: cphg-millerlab-plaqviewdev-service
  namespace: millerlab
spec:
  selector:
    app: cphg-millerlab-plaqviewdev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
