apiVersion: v1
kind: Service
metadata:
  name: cphg-millerlab-plaqview-v2-service
  namespace: millerlab
spec:
  selector:
    app: cphg-millerlab-plaqview-v2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
