apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/websocket-services: "cphg-millerlab-plaqview-v2-service"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "stickounet"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.org/proxy-connect-timeout: "600s"
    nginx.org/proxy-read-timeout: "600s"
    nginx.org/proxy-send-timeout: "600s"
#     acme.cert-manager.io/http01-edit-in-place: "true"
#     cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
  name: cphg-millerlab-plaqview-v2-tls-nginx-ingress
  namespace: millerlab
spec:
  rules:
    - host: plaqviewv2.pods.uvarc.io
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: cphg-millerlab-plaqview-v2-service
              port: 
                number: 8080
    - host: plaqview.uvadcos.io
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: cphg-millerlab-plaqview-v2-service
              port: 
                number: 8080
    - host: plaqviewv2.uvadcos.io
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: cphg-millerlab-plaqview-v2-service
              port: 
                number: 8080
#     #This section is only required if TLS is to be enabled for the Ingress
#   tls:
#       - hosts:
#           - plaqviewv2.pods.uvarc.io
#         secretName: cphg-millerlab-plaqview-v2-nginx-tls-ingress-secret
