apiVersion: apps/v1
kind: Deployment
metadata:
  name: cphg-millerlab-plaqview-archive-10082021-deployment
  namespace: millerlab
  labels:
    app: cphg-millerlab-plaqview-archive-10082021
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cphg-millerlab-plaqview-archive-10082021
  template:
    metadata:
      labels:
        app: cphg-millerlab-plaqview-archive-10082021
    spec:
      volumes:
      - name: cphg-millerlab-plaqview-archive-10082021-nfs-volume
        persistentVolumeClaim:
          claimName: cphg-millerlab-plaqview-archive-10082021-nfs-pvc # name of pvc
      containers:
      - name: cphg-millerlab-plaqview-archive-10082021-container
        image: quay.io/uvarc/plaqview:archive10082021
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cphg-millerlab-plaqview-archive-10082021-nfs-volume
          mountPath: /srv/shiny-server/data # mount inside of container
#        env:
#        - name:
#          value: ""
        resources:
          requests:
            memory: "15000Mi"
            cpu: "1"
          limits:
            memory: "16000Mi"
            cpu: "2"
            
